### ISSUE TITLE
when I try to pull the images，I get some error info "manifest unknown"

### ISSUE THREAD

**Issue by berg-wang** [yxwuxuanl/k8s-image-operator#1]
Error response from daemon: manifest for registry.cn-shenzhen.aliyuncs.com/lin2ur/k8s-image-operator:1.0.2 not found: manifest unknown: manifest unknown

I want to know how to download the images，I need deploy these images in my private k8s enviroment，look forward to the answer!

**Comment by yxwuxuanl** [comment]
The issue has been fixed, and you can also use the image from the `ghcr.io/yxwuxuanl/k8s-image-operator` repository.
